security_mode: sasl_ssl
kafka:
  broker:
    user: cp-kafka
    group: confluent
    config_file: /etc/kafka/server.properties
    jaas_config_file: /etc/kafka/kafka_server_jaas.conf
    systemd_env_file: /etc/kafka/kafka-env.sh
    systemd_config_file: /etc/systemd/system/kafka.service
    start_class: /bin/kafka-server-start
    log4j_config_file: /etc/kafka/log4j.properties
    service_name: kafka
    datadir:
      - /var/lib/kafka/data
    systemd:
      enabled: yes
      state: started
    config:
      group.initial.rebalance.delay.ms: 0
      log.retention.check.interval.ms: 300000
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      num.io.threads: 16
      num.network.threads: 8
      num.partitions: 1
      num.recovery.threads.per.data.dir: 2
      offsets.topic.replication.factor: 3
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      zookeeper.connection.timeout.ms: 6000
      min.insync.replicas: 2
      default.replication.factor: 3
      auto.create.topics.enable: "false"
      delete.topic.enable: "true"
