- name: create ssl certificate directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
- name: copy ssl related files
  copy:
    src: /var/ssl/private/
    dest: /var/ssl/private
