---
galaxy_info:
  author: David Harris
  description: Install and configure AWS CloudWatch Logs Agent
  company: Balihoo
  license: license (GPLv3)
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - 6
    - name: Amazon
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty

  categories:
    - cloud
    - cloud:ec2
    - monitoring
dependencies: []
