---
- name: install ncat
  yum:
    name: nmap-ncat
    state: present
- name: Install Confluent public key
  rpm_key:
    state: present
    key: https://packages.confluent.io/rpm/4.1/archive.key
- name: Add Confluent repository (dist)
  yum_repository:
    name: Confluent.dist
    description: Confluent repository (dist)
    file: confluent.repo
    baseurl: https://packages.confluent.io/rpm/4.1/7
    gpgkey: https://packages.confluent.io/rpm/4.1/archive.key
    gpgcheck: yes
    enabled: yes
- name: Add Confluent repository
  yum_repository:
    name: Confluent
    description: Confluent repository
    file: confluent.repo
    baseurl: https://packages.confluent.io/rpm/4.1
    gpgkey: https://packages.confluent.io/rpm/4.1/archive.key
    gpgcheck: yes
    enabled: yes
- name: Install Confluent Enterprise
  yum:
    name: confluent-platform-2.11
    state: present
