---
- name: gather EC2 facts
  ec2_metadata_facts:

- name: "Make /var/awslogs/state/ directory"
  file:
    path: /var/awslogs/state/
    state: directory
    mode: 755

- name: "Configure AWS CloudWatch Logs Agent"
  template:
    src: etc/awslogs/awslogs.conf.j2
    dest: /etc/awslogs/awslogs.conf
    owner: root
    group: root
    mode: 0644

- name: "Configure AWS CloudWatch Log Agent logging"
  template:
    src: etc/awslogs/awslogs.logging.conf.j2
    dest: /etc/awslogs/awslogs.logging.conf
    owner: root
    group: root
    mode: 0644
  when: awslogs_loglevel is defined

- name: "Configure AWS CloudWatch Logs Agent - Region"
  template:
    src: etc/awslogs/awscli.conf.j2
    dest: /etc/awslogs/awscli.conf
    owner: root
    group: root
    mode: 0644
